### ISSUE TITLE
Duplicate stack values

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/multi-value#6]
Would it be possible to duplicate a single stack value? Or do we need a helper function with which we push a single parameter multiple times as result?

I need it for a [Java to WebAssembly compiler](https://github.com/i-net-software/JWebAssembly).

I have no problem with such helper function if it needed.

**Comment by rossberg** [comment]
Wasm has local variables, which allow to express all stack manipulation. For most compilers, this ought to be easier than generating appropriate sequences of stack juggling instructions.

In any case, this question is somewhat unrelated to the multi-value proposal, so I'm closing the issue here. Please open on the design repo if you think the above does not answer your question.
